[policy]
version = 3
[javascript]
priority = "size-first"
assume_pristine_builtins = false
keep_published_function_names = true
[effort]
level = 8
[objective]
codecs = "raw"
[mangle]
identifiers = true
properties = true
pool_strings = true
