[javascript]
priority = "size-first"
optimization_level = 15
cost_model = "gzip"
assume_pristine_builtins = true
strip_console = true
candidate_search = "production"

[mangle]
identifiers = true
properties = true
pool_strings = true
