import { UUID, uuidv4, uuidv7 } from './uuidv7'
import {
  MINIMAL_FLAG_CALLED_EVENT_CAMPAIGN_PROPERTIES,
  MINIMAL_FLAG_CALLED_EVENT_PROPERTIES,
  createFlagsResponseFromFlagsAndPayloads,
  flagDetailsToResults,
  getFeatureFlagValue,
  getFlagValuesFromFlags,
  getPayloadsFromFlags,
  minimizeFlagCalledEventProperties,
  normalizeFlagsResponse,
  parsePayload,
  updateFlagValue,
} from './feature-flags'
import {
  cookieStateToProperties,
  cookieStoreFromHeader,
  getConsentCookieName,
  getPostHogCookieName,
  isOptedOut,
  parsePostHogCookie,
  readPostHogCookie,
  serializePostHogCookie,
} from './cookie'
import { apiHostFromConfig, endpointFor, flagsApiHostFromConfig, regionForHost, uiHostFromConfig } from './router'
import { rateLimitContext } from './rate-limit'
import { applyOffsets, clampFlushInterval, formatQueue, sortUnloadRequests } from './queue'
import { DEFAULT_BLOCKED_UA_STRS, isBlockedUA } from './bot-detection'
import { getPersonPropertiesHash, includes, isDistinctIdStringLike, stripLeadingDollar, trim } from './string-utils'
import { clampToRange, getRemoteConfigBool, getRemoteConfigNumber, isValidSampleRate } from './number-utils'
import {
  isBuiltin,
  isEmptyObject,
  isEmptyString,
  isKnownUnsafeEditableEvent,
  isKnownUnsafeEditableEventProperty,
  isNoLike,
  isNumber,
  isPositiveNumber,
  isPrimitive,
  isYesLike,
  knownUnsafeEditableEvent,
  knownUnsafeEditableEventProperty,
  noLikeValues,
  yesLikeValues,
} from './type-utils'
import { sanitizeString } from './json-utils'
import { removeTrailingSlash, stripUrlHash } from './url'
import {
  DEFAULT_EXCEPTION_RATE_LIMITER_BUCKET_SIZE,
  DEFAULT_EXCEPTION_RATE_LIMITER_REFILL_RATE,
  consumeBucketedRateLimit,
  resolveExceptionRateLimiterConfig,
} from './bucketed-rate-limit'

export function parseUuid(value: string): string {
  return UUID.parse(value).toString()
}

export function uuidFromFieldsV7(unixTsMs: number, randA: number, randBHi: number, randBLo: number): string {
  return UUID.fromFieldsV7(unixTsMs, randA, randBHi, randBLo).toString()
}

export function uuidToHex(value: string): string {
  return UUID.parse(value).toHex()
}

const kernel = {
  uuidv7,
  uuidv4,
  parseUuid,
  uuidFromFieldsV7,
  uuidToHex,
  normalizeFlagsResponse,
  getFeatureFlagValue,
  getFlagValuesFromFlags,
  getPayloadsFromFlags,
  createFlagsResponseFromFlagsAndPayloads,
  minimizeFlagCalledEventProperties,
  parsePayload,
  updateFlagValue,
  flagDetailsToResults,
  MINIMAL_FLAG_CALLED_EVENT_PROPERTIES,
  MINIMAL_FLAG_CALLED_EVENT_CAMPAIGN_PROPERTIES,
  getPostHogCookieName,
  serializePostHogCookie,
  parsePostHogCookie,
  cookieStoreFromHeader,
  readPostHogCookie,
  cookieStateToProperties,
  getConsentCookieName,
  isOptedOut,
  apiHostFromConfig,
  flagsApiHostFromConfig,
  uiHostFromConfig,
  regionForHost,
  endpointFor,
  rateLimitContext,
  clampFlushInterval,
  formatQueue,
  applyOffsets,
  sortUnloadRequests,
  DEFAULT_BLOCKED_UA_STRS,
  isBlockedUA,
  includes,
  trim,
  stripLeadingDollar,
  isDistinctIdStringLike,
  getPersonPropertiesHash,
  clampToRange,
  getRemoteConfigBool,
  getRemoteConfigNumber,
  isValidSampleRate,
  isNumber,
  isEmptyObject,
  isEmptyString,
  isPositiveNumber,
  isPrimitive,
  isBuiltin,
  isYesLike,
  isNoLike,
  isKnownUnsafeEditableEvent,
  isKnownUnsafeEditableEventProperty,
  knownUnsafeEditableEvent,
  knownUnsafeEditableEventProperty,
  yesLikeValues,
  noLikeValues,
  sanitizeString,
  removeTrailingSlash,
  stripUrlHash,
  DEFAULT_EXCEPTION_RATE_LIMITER_REFILL_RATE,
  DEFAULT_EXCEPTION_RATE_LIMITER_BUCKET_SIZE,
  resolveExceptionRateLimiterConfig,
  consumeBucketedRateLimit,
}

export {
  uuidv7,
  uuidv4,
  MINIMAL_FLAG_CALLED_EVENT_PROPERTIES,
  MINIMAL_FLAG_CALLED_EVENT_CAMPAIGN_PROPERTIES,
  normalizeFlagsResponse,
  getFeatureFlagValue,
  getFlagValuesFromFlags,
  getPayloadsFromFlags,
  createFlagsResponseFromFlagsAndPayloads,
  minimizeFlagCalledEventProperties,
  parsePayload,
  updateFlagValue,
  flagDetailsToResults,
  getPostHogCookieName,
  serializePostHogCookie,
  parsePostHogCookie,
  cookieStoreFromHeader,
  readPostHogCookie,
  cookieStateToProperties,
  getConsentCookieName,
  isOptedOut,
  apiHostFromConfig,
  flagsApiHostFromConfig,
  uiHostFromConfig,
  regionForHost,
  endpointFor,
  rateLimitContext,
  clampFlushInterval,
  formatQueue,
  applyOffsets,
  sortUnloadRequests,
  DEFAULT_BLOCKED_UA_STRS,
  isBlockedUA,
  includes,
  trim,
  stripLeadingDollar,
  isDistinctIdStringLike,
  getPersonPropertiesHash,
  clampToRange,
  getRemoteConfigBool,
  getRemoteConfigNumber,
  isValidSampleRate,
  isNumber,
  isEmptyObject,
  isEmptyString,
  isPositiveNumber,
  isPrimitive,
  isBuiltin,
  isYesLike,
  isNoLike,
  isKnownUnsafeEditableEvent,
  isKnownUnsafeEditableEventProperty,
  knownUnsafeEditableEvent,
  knownUnsafeEditableEventProperty,
  yesLikeValues,
  noLikeValues,
  sanitizeString,
  removeTrailingSlash,
  stripUrlHash,
  DEFAULT_EXCEPTION_RATE_LIMITER_REFILL_RATE,
  DEFAULT_EXCEPTION_RATE_LIMITER_BUCKET_SIZE,
  resolveExceptionRateLimiterConfig,
  consumeBucketedRateLimit,
}

export default kernel
